CREATE TABLE IF NOT EXISTS `questions_mrcgp` (
  `id` varchar(50) PRIMARY KEY,
  `exam` varchar(255) NOT NULL,
  `domain` varchar(255),
  `specialty` varchar(255) NOT NULL,
  `difficulty` enum('Easy', 'Medium', 'Hard') DEFAULT 'Medium',
  `question` longtext NOT NULL,
  `optionA` longtext NOT NULL,
  `optionB` longtext NOT NULL,
  `optionC` longtext NOT NULL,
  `optionD` longtext NOT NULL,
  `optionE` longtext,
  `correctAnswer` varchar(10) NOT NULL,
  `explanationCorrect` longtext,
  `explanationA` longtext,
  `explanationB` longtext,
  `explanationC` longtext,
  `explanationD` longtext,
  `explanationE` longtext,
  `referenceText` longtext,
  `tags` json,
  `createdAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_specialty` (`specialty`),
  KEY `idx_difficulty` (`difficulty`),
  KEY `idx_exam` (`exam`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
