import { storagePut } from './storage';
import { notifyOwner } from './_core/notification';

interface ExamReport {
  userId: number;
  userEmail: string;
  userName: string;
  examName: string;
  score: number;
  totalQuestions: number;
  accuracy: number;
  specialtyBreakdown: Record<string, number>;
  completedAt: Date;
  pdfUrl?: string;
}

interface ConsultationReport {
  userId: number;
  userEmail: string;
  userName: string;
  caseTitle: string;
  transcript: string;
  domainScores: Record<string, number>;
  feedback: string;
  completedAt: Date;
  pdfUrl?: string;
}

/**
 * Send exam report email with PDF attachment
 */
export async function sendExamReportEmail(report: ExamReport) {
  try {
    // Generate PDF report
    const pdfBuffer = await generateExamPDF(report);
    
    // Upload PDF to storage
    const { url: pdfUrl } = await storagePut(
      `reports/exam-${report.userId}-${Date.now()}.pdf`,
      pdfBuffer,
      'application/pdf'
    );

    // Prepare email content
    const emailContent = `
Dear ${report.userName},

Congratulations on completing the ${report.examName} mock exam!

**Your Results:**
- Score: ${report.score}/${report.totalQuestions}
- Accuracy: ${report.accuracy}%
- Completed: ${report.completedAt.toLocaleDateString()}

**Specialty Breakdown:**
${Object.entries(report.specialtyBreakdown)
  .map(([specialty, score]) => `- ${specialty}: ${score}%`)
  .join('\n')}

Your detailed report is attached. Review the areas where you need improvement and focus your study accordingly.

Best regards,
Question Grove 360 Team
    `;

    // Send email via Resend
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'noreply@questiongrove360.com',
        to: report.userEmail,
        subject: `Your ${report.examName} Results - ${report.accuracy}% Accuracy`,
        html: emailContent,
        attachments: [
          {
            filename: `exam-report-${report.examName}.pdf`,
            content: pdfBuffer.toString('base64'),
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Failed to send email: ${response.statusText}`);
    }

    return { success: true, pdfUrl };
  } catch (error) {
    console.error('Error sending exam report email:', error);
    throw error;
  }
}

/**
 * Send consultation report email with feedback
 */
export async function sendConsultationReportEmail(report: ConsultationReport) {
  try {
    // Generate PDF report
    const pdfBuffer = await generateConsultationPDF(report);
    
    // Upload PDF to storage
    const { url: pdfUrl } = await storagePut(
      `reports/consultation-${report.userId}-${Date.now()}.pdf`,
      pdfBuffer,
      'application/pdf'
    );

    // Prepare email content
    const emailContent = `
Dear ${report.userName},

Thank you for completing the SCA consultation simulation: ${report.caseTitle}

**Your Performance:**
${Object.entries(report.domainScores)
  .map(([domain, score]) => `- ${domain}: ${score}/10`)
  .join('\n')}

**Feedback:**
${report.feedback}

Your detailed report is attached. Use this feedback to improve your clinical skills and prepare for the actual exam.

Best regards,
Question Grove 360 Team
    `;

    // Send email via Resend
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'noreply@questiongrove360.com',
        to: report.userEmail,
        subject: `Your SCA Consultation Results - ${report.caseTitle}`,
        html: emailContent,
        attachments: [
          {
            filename: `consultation-report-${report.caseTitle}.pdf`,
            content: pdfBuffer.toString('base64'),
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Failed to send email: ${response.statusText}`);
    }

    return { success: true, pdfUrl };
  } catch (error) {
    console.error('Error sending consultation report email:', error);
    throw error;
  }
}

/**
 * Generate exam PDF report
 */
function generateExamPDF(report: ExamReport): Buffer {
  // This would use a PDF generation library like pdf-lib or pdfkit
  // For now, return a placeholder buffer
  const pdfContent = `
EXAM REPORT
===========

Exam: ${report.examName}
Date: ${report.completedAt.toLocaleDateString()}
User: ${report.userName}

Score: ${report.score}/${report.totalQuestions}
Accuracy: ${report.accuracy}%

Specialty Breakdown:
${Object.entries(report.specialtyBreakdown)
  .map(([specialty, score]) => `${specialty}: ${score}%`)
  .join('\n')}

Generated by Question Grove 360
  `;

  return Buffer.from(pdfContent, 'utf-8');
}

/**
 * Generate consultation PDF report
 */
async function generateConsultationPDF(report: ConsultationReport): Promise<Buffer> {
  const pdfContent = `
CONSULTATION REPORT
===================

Case: ${report.caseTitle}
Date: ${report.completedAt.toLocaleDateString()}
User: ${report.userName}

Domain Scores:
${Object.entries(report.domainScores)
  .map(([domain, score]) => `${domain}: ${score}/10`)
  .join('\n')}

Feedback:
${report.feedback}

Transcript:
${report.transcript}

Generated by Question Grove 360
  `;

  return Buffer.from(pdfContent, 'utf-8');
}

/**
 * Schedule email report to be sent (for async processing)
 */
export async function scheduleEmailReport(
  type: 'exam' | 'consultation',
  report: ExamReport | ConsultationReport,
  delayMs: number = 0
) {
  return new Promise((resolve) => {
    setTimeout(async () => {
      try {
        if (type === 'exam') {
          const result = await sendExamReportEmail(report as ExamReport);
          resolve(result);
        } else {
          const result = await sendConsultationReportEmail(report as ConsultationReport);
          resolve(result);
        }
      } catch (error) {
        console.error(`Failed to send ${type} report email:`, error);
        resolve({ success: false, error });
      }
    }, delayMs);
  });
}

// ============================================================
// Email Trigger System (Owner Notifications)
// ============================================================

export type EmailTriggerType =
  | "welcome"
  | "study_reminder"
  | "exam_result"
  | "subscription_activated"
  | "subscription_expiring"
  | "weekly_progress";

interface EmailTriggerPayload {
  type: EmailTriggerType;
  userId: number;
  userName?: string;
  data?: Record<string, any>;
}

/**
 * Trigger an owner notification based on the event type.
 * Returns true if the notification was sent successfully.
 */
export async function triggerEmailNotification(payload: EmailTriggerPayload): Promise<boolean> {
  const { type, userName = "Unknown User", data } = payload;

  let title: string;
  let content: string;

  switch (type) {
    case "welcome":
      title = `New User Registration: ${userName}`;
      content = `A new user "${userName}" has registered on Question Grove 360.\n\nTimestamp: ${new Date().toISOString()}`;
      break;
    case "study_reminder":
      title = `Study Reminder Alert: ${userName}`;
      content = `User "${userName}" hasn't studied in a while.\nCurrent streak: ${data?.streak || 0} days\nLast active: ${data?.lastActive || "Unknown"}`;
      break;
    case "exam_result":
      title = `Exam Result: ${userName} - ${data?.passed ? "PASSED" : "FAILED"}`;
      content = `User "${userName}" completed "${data?.examName || "Mock Exam"}".\nScore: ${data?.score || 0}/${data?.totalQuestions || 0} (${Math.round(((data?.score || 0) / (data?.totalQuestions || 1)) * 100)}%)\nResult: ${data?.passed ? "PASSED" : "FAILED"}`;
      break;
    case "subscription_activated":
      title = `Subscription Activated: ${userName}`;
      content = `User "${userName}" has activated a ${data?.plan || "Premium"} subscription.\nTimestamp: ${new Date().toISOString()}`;
      break;
    case "subscription_expiring":
      title = `Subscription Expiring: ${userName}`;
      content = `User "${userName}"'s subscription is expiring soon.\nExpires at: ${data?.expiresAt || "Unknown"}`;
      break;
    case "weekly_progress":
      title = `Weekly Progress: ${userName}`;
      content = `Questions answered: ${data?.questionsAnswered || 0}\nCorrect rate: ${data?.correctRate || 0}%\nStudy hours: ${data?.studyHours || 0}`;
      break;
    default:
      console.warn(`[EmailService] Unknown trigger type: ${type}`);
      return false;
  }

  try {
    const result = await notifyOwner({ title, content });
    console.log(`[EmailService] Notification ${result ? "sent" : "failed"}: ${type} for user ${payload.userId}`);
    return result;
  } catch (error) {
    console.error(`[EmailService] Error sending notification:`, error);
    return false;
  }
}

/**
 * Trigger a welcome notification when a new user registers.
 */
export async function triggerWelcomeNotification(userId: number, userName: string): Promise<boolean> {
  return triggerEmailNotification({ type: "welcome", userId, userName });
}

/**
 * Trigger an exam result notification.
 */
export async function triggerExamResultNotification(
  userId: number,
  userName: string,
  examName: string,
  score: number,
  totalQuestions: number,
  passed: boolean
): Promise<boolean> {
  return triggerEmailNotification({
    type: "exam_result",
    userId,
    userName,
    data: { examName, score, totalQuestions, passed },
  });
}

/**
 * Trigger a subscription activation notification.
 */
export async function triggerSubscriptionNotification(
  userId: number,
  userName: string,
  plan: string
): Promise<boolean> {
  return triggerEmailNotification({
    type: "subscription_activated",
    userId,
    userName,
    data: { plan },
  });
}
