import "dotenv/config";
import mysql from "mysql2/promise";
import fs from "fs";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error("DATABASE_URL not set"); process.exit(1); }

async function main() {
  const conn = await mysql.createConnection(DATABASE_URL + "&multipleStatements=true");
  const outFile = "/home/ubuntu/questiongrove360_backup_2026-08-18.sql";
  let sql = "-- Question Grove 360 Full Database Dump\n-- Date: 2026-08-18\n-- Generated by dump_db.mjs\n\nSET FOREIGN_KEY_CHECKS=0;\n\n";

  // Get all tables
  const [tables] = await conn.query("SHOW TABLES");
  const tableKey = Object.keys(tables[0])[0];
  const tableNames = tables.map(t => t[tableKey]);

  console.log(`Found ${tableNames.length} tables`);
  const rowCounts = {};

  for (const table of tableNames) {
    // CREATE TABLE
    const [createResult] = await conn.query(`SHOW CREATE TABLE \`${table}\``);
    const createStmt = createResult[0]["Create Table"];
    sql += `-- Table: ${table}\nDROP TABLE IF EXISTS \`${table}\`;\n${createStmt};\n\n`;

    // Row count
    const [countResult] = await conn.query(`SELECT COUNT(*) as cnt FROM \`${table}\``);
    const rowCount = countResult[0].cnt;
    rowCounts[table] = rowCount;

    if (rowCount === 0) {
      sql += `-- ${table}: 0 rows\n\n`;
      continue;
    }

    // Get all rows in batches of 500
    const batchSize = 500;
    for (let offset = 0; offset < rowCount; offset += batchSize) {
      const [rows] = await conn.query(`SELECT * FROM \`${table}\` LIMIT ${batchSize} OFFSET ${offset}`);
      if (rows.length === 0) break;

      const cols = Object.keys(rows[0]);
      const colList = cols.map(c => `\`${c}\``).join(", ");

      const values = rows.map(row => {
        const vals = cols.map(c => {
          const v = row[c];
          if (v === null || v === undefined) return "NULL";
          if (v instanceof Date) return `'${v.toISOString().slice(0, 19).replace("T", " ")}'`;
          if (typeof v === "number" || typeof v === "bigint") return String(v);
          if (typeof v === "boolean") return v ? "1" : "0";
          if (Buffer.isBuffer(v)) return `X'${v.toString("hex")}'`;
          return `'${String(v).replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n").replace(/\r/g, "\\r")}'`;
        });
        return `(${vals.join(", ")})`;
      });

      sql += `INSERT INTO \`${table}\` (${colList}) VALUES\n${values.join(",\n")};\n\n`;
    }

    console.log(`  ${table}: ${rowCount} rows`);
  }

  sql += "SET FOREIGN_KEY_CHECKS=1;\n";
  fs.writeFileSync(outFile, sql, "utf8");

  const stats = fs.statSync(outFile);
  const sizeMB = (stats.size / (1024 * 1024)).toFixed(2);

  console.log(`\nDump complete: ${outFile}`);
  console.log(`File size: ${sizeMB} MB`);
  console.log(`\nRow counts:`);
  for (const [table, count] of Object.entries(rowCounts)) {
    console.log(`  ${table}: ${count}`);
  }
  console.log(`\nTotal tables: ${tableNames.length}`);

  await conn.end();
}

main().catch(err => { console.error(err); process.exit(1); });
